#!/bin/zsh

filtre='\?'

questions_modales="\b(tou(|te)s|existe|y[  ]a-t-il|certains|partout|(nulle|quelque)[  ]part|toujours|parfois|jamais)\b"

./06-toutes_questions_totales | \
    grep "$filtre" | \
    egrep -i "$questions_quantifiees"
