#!/bin/zsh

filtre='\?'

questions_quantifiees="\b(\
tou(s|t(|e(|s)))|\
existe|\
y[  ]a-t-il|\
certains|\
quelque[  ]chose|\
partout|\
(nulle|quelque)[  ]part|\
toujours|\
parfois|\
jamais\
)\b"

./06-toutes_questions_totales | \
    grep "$filtre" | \
    egrep -i "$questions_quantifiees"
