#!/bin/zsh

# nombre="10"
filtre='\?'

# questions_partielles="((Q|[:,] q)u(i|e|')|((À|[:,] à)|(D|[:,] d)e)[  ]qu((|o)i|el)|(Q|[:,] q)u'est-ce|((D|[:,] d)ans|(E|[:,] e)n)[  ]qu(el|oi)|(C|[:,] c)ombien|(C|[:,] c)omment|(O|[:,] o)ù|(Q|[:,] q)uand|(P|[:,] p)ourquoi)"

questions_modales="\b(tou(|te)s|existe|y[  ]a-t-il|certains|partout|(nulle|quelque)[  ]part|toujours|parfois|jamais)\b"

./06-toutes_questions_totales | \
    grep "$filtre" | \
    egrep -i "$questions_modales" # | \
#    shuf -n"$nombre" | \
#    sed s/'^'/'- '/g
