#!/bin/zsh

# nombre="10"
filtre='\?'

questions_partielles="(\
((À|[:,] à)[  ]qu(el[^q]|i|oi))|\
((C|[:,] c)ombien)|\
((C|[:,] c)omment)|\
((D|[:,] d)ans)|\
((D|[:,] d)e[  ]qu((|o)i|el))|\
((E|[:,] e)n[  ]qu(el|oi))|\
((Q|[:,] q)u(i|e|\'))|\
((Q|[:,] q)u\'est-ce)|\
((O|[:,] o)ù)|\
((P|[:,] p)ar[  ]qu(el[^q]|i|oi))|\
((P|[:,] p)ourquoi)|\
((Q|[:,] q)uand)\
((S|[:,] s)ur[  ]qu(el[^q]|i|oi))\
)"

./00-sujets | \
    grep "$filtre" | \
    egrep -v "$questions_partielles" | \
#    shuf -n"$nombre" | \
    sed s/'^'/'- '/g
