#!/bin/zsh

filtre='\?'

questions_modales="\b(\
faut-il|\
doi(s|t)|\
devons|\
peut|\
puis|\
nécessaire|\
possible|\
contingent|\
obligatoire|\
interdit|\
autorisé|\
permis\
)\b"

./06-toutes_questions_totales | \
    grep "$filtre" | \
    egrep -i "$questions_modales"
