#!/bin/zsh

# nombre="10"
filtre='\?'
questions_partielles="((Q|[:,] q)u(i|e|')|((À|[:,] à)|(D|[:,] d)e)[  ]qu((|o)i|el)|(Q|[:,] q)u'est-ce|((D|[:,] d)ans|(E|[:,] e)n)[  ]qu(el|oi)|(C|[:,] c)ombien|(C|[:,] c)omment|(O|[:,] o)ù|(Q|[:,] q)uand|(P|[:,] p)ourquoi)"

./00-sujets | \
    grep "$filtre" | \
    egrep "$questions_partielles" | \
#    shuf -n"$nombre" | \
    sed s/'^'/'- '/g
