#+TITLE:     Sujets de dissertation de philosophie
#+AUTHOR:    Baptiste Mélès
#+EMAIL:     baptiste.meles@gmail.com
#+DATE:      11 octobre 2019
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  fr
#+OPTIONS:   H:4 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage[frenchb]{babel}
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage{multicol}
#+LATEX_HEADER: \DeclareUnicodeCharacter{00A0}{~}
#+LATEX_HEADER: \DeclareUnicodeCharacter{200B}{}


Voici des sujets pour s'entraîner à la dissertation[fn:1]. Pour vous
entraîner, il suffit de rédiger :

1. une introduction : définitions, tension, problématique ;

2. un plan détaillé (aucun nom de philosophe ne doit apparaître dans les
   titres des parties et sous-parties) ;

3. une courte conclusion répondant clairement à la problématique.

\begin{multicols}{2}
\noindent Peut-on renoncer à comprendre ? \par
\noindent Y a-t-il une éducation du goût ? \par
\noindent L'extraordinaire \par
\noindent Qu'est-ce qu'un monstre ? \par
\noindent À qui devons-nous obéir ? \par
\noindent Peut-on échapper au temps ? \par
\noindent Pourquoi se divertir ? \par
\noindent Y a-t-il de l'impensable ? \par
\noindent Le possible \par
\noindent Qu'est-ce qu'une expérience? \par
\noindent Y a-t-il des limites à la conscience ? \par
\noindent La chance \par
\noindent L'incertitude \par
\noindent Qu'est-ce qu'être efficace en politique ? \par
\noindent Tout est-il politique ? \par
\noindent L'universel \par
\noindent Ai-je un corps ? \par
\noindent Ignorer \par
\noindent La métaphysique est-elle une science ? \par
\noindent Que nous apprennent les mythes ? \par
\noindent Qu'est-ce que traduire ? \par
\noindent Le désir de savoir est-il naturel ? \par
\noindent L'insurrection est-elle un droit ? \par
\noindent Y a-t-il des leçons de l'histoire ? \par
\noindent L'égalité est-elle une condition de la liberté ? \par
\noindent Le passé \par
\noindent La connaissance de soi \par
\noindent L'objet de l'amour \par
\noindent Pourquoi raconter des histoires ? \par
\noindent L'amour-propre \par
\noindent Qui suis-je ? \par
\noindent Existe-t-il un art de penser ? \par
\noindent La mort de Dieu \par
\noindent Connaître l'infini \par
\noindent L'homme est-il un loup pour l'homme ? \par
\noindent L'œuvre d'art doit-elle nous émouvoir ? \par
\noindent La vérité en art \par
\noindent Vérité et certitude \par
\noindent L'enfant et l'adulte \par
\noindent Les animaux pensent-ils ? \par
\noindent Le beau a-t-il une histoire ? \par
\noindent L'éternité \par
\noindent L'interprétation \par
\noindent Peut-on penser sans concept ? \par
\noindent Entendre raison \par
\noindent Qu'est-ce que faire preuve d'humanité ? \par
\noindent L'histoire a-t-elle un sens ? \par
\noindent L'aveu \par
\noindent Prévoir \par
\noindent Que recherche l'artiste ? \par
\noindent Peut-on rester sceptique ? \par
\noindent L'outil \par
\noindent Le vrai et le faux \par
\noindent Faut-il une théorie de la connaissance ? \par
\noindent L’acte et l’œuvre \par
\noindent Qu’est-ce qu'un réfutation ? \par
\noindent L’exception \par
\noindent Le bavardage \par
\noindent La philosophie est-elle abstraite ? \par
\noindent L’éternité \par
\noindent L’homme est-il raisonnable par nature ? \par
\noindent Peut-on tout dire ? \par
\noindent Y a-t-il des actes de pensée ? \par
\noindent Tuer le temps \par
\noindent L’imprévisible \par
\noindent Qu’y a-t-il ? \par
\noindent Qu’est-ce qu’un accident ? \par
\noindent L’opinion \par
\noindent La gauche et la droite \par
\noindent Le privé et le public \par
\noindent Peut-on tout démontrer ? \par
\noindent Quel est l’objet de l’histoire ? \par
\noindent La cohérence \par
\noindent Que nul n’entre ici s’il n’est géomètre. \par
\noindent Histoire et géographie \par
\noindent Voir \par
\noindent La conscience a-t-elle des moments ? \par
\noindent L’argument d’autorité. \par
\noindent La désobéissance \par
\noindent Rêvons-nous ? \par
\noindent L’inhumain \par
\noindent Qu’est-ce qu’un principe ? \par
\noindent Y a-t-il une langue de la philosophie ? \par
\noindent L’introspection est-elle une connaissance ? \par
\noindent L’homme est-il un animal comme les autres ? \par
\noindent La nature est-elle bien faite ? \par
\noindent L’ordre. \par
\noindent La démocratie \par
\noindent Peut-on penser sans ordre ? \par
\noindent Qu’est-ce qu’un monstre ? \par
\noindent Le temps existe-t-il ? \par
\noindent Qu’est-ce qu’un auteur ? \par
\noindent Qu’est-ce qu’être ? \par
\noindent Peut-on être sceptique ? \par
\noindent Qu’est-ce qu’interpréter ? \par
\noindent Qu’est-ce qu’un peuple ? \par
\noindent Peut-on séparer l’homme et l’œuvre ? \par
\noindent Peut-on ne pas être soi-même ? \par
\noindent À quoi reconnaît-on une œuvre d’art ? \par
\noindent La haine de la raison \par
\noindent Comment penser le mouvement ? \par
\noindent Y a-t-il des régressions historiques ? \par
\noindent Suis-je seul au monde ? \par
\noindent Qu’est-ce qu’un monde ? \par
\noindent La famille \par
\noindent Y a-t-il des guerres justes ? \par
\noindent Le mot juste. \par
\noindent L’identité collective \par
\noindent La loi \par
\noindent Qu’est-ce qu’une question ? \par
\noindent Qui fait l’histoire ? \par
\noindent Qu’est-ce qu’une maladie ? \par
\noindent L’irrationnel \par
\noindent Qu’est-ce qu’un auteur ? \par
\noindent Qu’est-ce qui fait la force de la loi ? \par
\noindent La superstition \par
\noindent Peut-on s’en tenir au présent ? \par
\noindent L’emploi du temps \par
\noindent Y a-t-il des expériences métaphysiques ? \par
\noindent Le spectacle de la nature \par
\noindent Habiter le monde \par
\noindent L’état de droit \par
\noindent La servitude \par
\noindent La perspective \par
\noindent Qu’est-ce qu’un monstre ? \par
\noindent La reconnaissance \par
\noindent Le beau a-t-il une histoire ? \par
\noindent L’événement \par
\noindent Plaisir et douleur \par
\noindent L’interprétation \par
\noindent La solitude \par
\noindent L’illusion \par
\noindent L’observation \par
\noindent La raison d’Etat \par
\noindent L’harmonie \par
\noindent Justice et force \par
\noindent Le paysage \par
\noindent Apprend-on à voir ? \par
\noindent L’habitude \par
\noindent La simplicité \par
\noindent Faut-il se délivrer de la peur ? \par
\noindent Faut-il vouloir la transparence ? \par
\noindent Le langage est-il un instrument ? \par
\noindent L’identité personnelle \par
\noindent L’avocat du diable \par
\noindent Peut-il y avoir un droit de la guerre ? \par
\noindent Qu’est-ce qu’une croyance rationnelle ? \par
\noindent La désobéissance civile \par
\noindent L’ennemi \par
\noindent Qu’est-ce qu’une décision politique ? \par
\noindent Penser par soi-même \par
\noindent Être hors de soi \par
\noindent Pourquoi punir ? \par
\noindent L’artiste est-il un créateur ? \par
\noindent Peut-on tout exprimer ? \par
\noindent Cause et loi \par
\noindent Qu’est-ce qu’un mythe ? \par
\noindent Pouvons-nous être objectifs ? \par
\noindent L’étranger \par
\noindent L’imaginaire \par
\noindent Quel usage peut-on faire des fictions ? \par
\noindent Faire la paix \par
\noindent Le mouvement \par
\noindent La loi et la coutume \par
\noindent Quel est l’objet de l’amour ? \par
\noindent Qu’est-ce qu’une crise ? \par
\noindent Apprend-on à être artiste ? \par
\noindent L’oubli \par
\noindent L’amour de la vérité \par
\noindent Les œuvres d’art sont-elles éternelles ? \par
\noindent Le hasard \par
\noindent Peut-on être citoyen du monde ? \par
\noindent Y a-t-il des limites à la connaissance ? \par
\noindent L’apparence \par
\noindent La critique \par
\noindent La souveraineté peut-elle se partager ? \par
\noindent Qu’est-ce qui est réel ? \par
\noindent La justice sociale \par
\noindent L’immortalité \par
\end{multicols}


* Footnotes

[fn:1] Ces sujets sont tirés du rapport du jury du concours oral pour
l'année 2018 de l'École normale supérieure de Paris
(http://www.ens.fr/sites/default/files/2018_al_philo_oral_epreuve_commune.pdf).
Les sujets ont été proposés par Fabienne Baghdassarian, François Calori,
Pascale Gillot, Laurent Lavaud, Baptiste Mélès et Pauline Nadrigny.

