#!/bin/zsh

echo "DEUX-POINTS"
grep ' :' capes*.txt agregation*.txt ens*.txt
echo

echo "POINT-VIRGULE"
grep ' ;' capes*.txt agregation*.txt ens*.txt
echo

echo "POINT D'EXCLAMATION"
grep ' !' capes*.txt agregation*.txt ens*.txt
echo

echo "POINT D'INTERROGATION"
grep ' ?' capes*.txt agregation*.txt ens*.txt
echo

echo "GUILLEMETS"
grep '« ' capes*.txt agregation*.txt ens*.txt
grep ' »' capes*.txt agregation*.txt ens*.txt
echo

echo "À"
grep 'à ' capes*.txt agregation*.txt ens*.txt
